10 cicd
davay-project/davay_posmotrim_android pull request #35
Opened 2024-02-26 15:14 UTC by dvBuslaev

2024-02-28 20:07 UTC, dvBuslaev commented
@n-shvedov27 все, проект собирается. скрой мой позор плиз и сделай сквашни мои комиты до 1)

2024-02-29 03:58 UTC, n-shvedov27 requested changes

2024-02-29 03:58 UTC, n-shvedov27 commented on .github/workflows/github-actions.yml
> +        run: chmod +x gradlew
А без этого разве не работает?

2024-02-29 03:58 UTC, n-shvedov27 commented on app/build.gradle.kts
> +    dependencies {
И это не совсем понял зачем

2024-02-29 04:11 UTC, n-shvedov27 commented on .github/workflows/github-actions.yml
> +        run: chmod +x gradlew
Хм, сейчас у нас действительно gradlew почему-то не исполняемый
Сделай тогда локально 
chmod +x gradlew
И запуш изменения gradlew, а из github-actions.yml это убрать можно

2024-02-29 13:30 UTC, dvBuslaev commented on app/build.gradle.kts
> +    dependencies {
без этого он не мог найти зависимости для проекта

2024-02-29 15:13 UTC, dvBuslaev commented on .github/workflows/github-actions.yml
> +        run: chmod +x gradlew
не оч понял, при каждой проверке он качает градл и дает к нему доступ на исполнение, как это исправит то что я своему локальному градлу дам разрешение?

2024-02-29 18:13 UTC, n-shvedov27 approved these changes

2024-02-29 18:13 UTC, merged